server:
  port: 9999

management:
  endpoints:
    prometheus:
      enable: true
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


spring:
  enhancetp:
    datasource:
      nacos:
        server-addr: "${spring.cloud.nacos.config.server-addr}"
        groupId: DEFAULT_GROUP